// GENERATED by scripts/build_skill_refs.py from references/fingerprint.json - do not edit by hand.
// Measured over 6 Apple recap videos (33187 frames). Medians unless noted.

export const FPS = 30;

export type SpringCfg = {damping: number; stiffness: number; mass: number};
export type Bezier = readonly [number, number, number, number];

export const SPRING = {
  /** median fitted entry spring of designer typography (n=43), corrected by the pipeline
   *  calibration (time scale 1.19). Use WITHOUT durationInFrames to reproduce the curve. */
  textIn: {damping: 14.0, stiffness: 82.1, mass: 1},
  textOut: {damping: 14.0, stiffness: 123.1, mass: 1},
  camera: {damping: 30, stiffness: 60, mass: 1},
} satisfies Record<string, SpringCfg>;

export const EASE = {
  /** median fitted cubic-bezier of typography entries */
  textIn: [0.341, 0.111, 0.726, 0.8] as Bezier,
  textOut: [0.32, 0.422, 0.494, 0.354] as Bezier,
  camera: [0.45, 0, 0.2, 1] as Bezier,
};

export const DURATION = {
  /** animated typography entries, median frames (p10..p90 5.0..31.6) */
  textInFrames: 8,
  textOutFrames: 4,
  /** typography hold, median frames (p10..p90 5.4..80.6) */
  holdFrames: 28,
  /** shot length, median frames (p10..p90 13.0..173.5) */
  shotFrames: 56,
  wordStaggerFrames: 3,
  letterStaggerFrames: 1,
  transitionFrames: 8,
};

export const START = {
  /** median start scale of entries that scale down into place */
  scaleDown: 1.1,
  scaleUp: 0.93,
  /** median start blur (px at 1080p) of entries that blur in */
  blurPx: 14.4,
  /** median |start y offset| in % of frame height for sliding entries */
  slideYPctH: 1.83,
};

export const TYPE = {
  family: '"SF Pro Display", "SF Pro", -apple-system, BlinkMacSystemFont, "Inter", "Helvetica Neue", Arial, sans-serif',
  /** cap height in % of frame height: hero = p90, headline = p50, title = p25, caption = p10 */
  capHeightPct: {hero: 20.23, headline: 6.67, title: 5.43, caption: 3.25},
  /** SF Pro weight from measured stroke/cap, calibrated on renders at known weights (median 600.0) */
  weight: {hero: 600, headline: 600, title: 600, caption: 500},
  /** line pitch / cap height 1.53 -> line-height in em for SF Pro Display */
  lineHeight: 1.079,
  letterSpacingEm: -0.015,
};

export const COLOR = {
  black: '#000000',
  white: '#ffffff',
  offWhite: '#f5f5f7',
  graphite: '#1d1d1f',
  gray: '#86868b',
  /** most frequent measured typography colours */
  measured: ["#080808", "#0b0b0b", "#0e0e0e", "#1a1a1a", "#0f0f0f", "#0c0c0d"],
};

export const AUDIO = {
  /** median integrated loudness of the Apple recaps (p10..p90 -20.4..-16.6) */
  lufs: -17.4,
  truePeakDb: -2.0,
  bpm: 118.8,
  musicUnderVoiceDb: -12,
};
