// GENERATED by scripts/build_skill_refs.py from references/fingerprint.json - do not edit by hand.
// Measured over 6 Apple recap videos (33187 frames). Medians unless noted.

export const FPS = 30;

export type SpringCfg = {damping: number; stiffness: number; mass: number};
export type Bezier = readonly [number, number, number, number];

export const SPRING = {
  /** median fitted entry spring of designer typography (n=41), corrected by the pipeline
   *  calibration (time scale 1.19). Use WITHOUT durationInFrames to reproduce the curve. */
  textIn: {damping: 15.3, stiffness: 115.0, mass: 1},
  textOut: {damping: 15.3, stiffness: 172.5, mass: 1},
  camera: {damping: 30, stiffness: 60, mass: 1},
} satisfies Record<string, SpringCfg>;

export const EASE = {
  /** median fitted cubic-bezier of typography entries */
  textIn: [0.205, 0.137, 0.732, 0.802] as Bezier,
  textOut: [0.026, 0.422, 0.943, 0.649] as Bezier,
  camera: [0.45, 0, 0.2, 1] as Bezier,
};

export const DURATION = {
  /** animated typography entries, median frames (p10..p90 5.0..24.0) */
  textInFrames: 8,
  textOutFrames: 2,
  /** typography hold, median frames (p10..p90 10.0..80.6) */
  holdFrames: 33,
  /** shot length, median frames (p10..p90 13.0..173.5) */
  shotFrames: 56,
  wordStaggerFrames: 3,
  letterStaggerFrames: 1,
  transitionFrames: 8,
};

export const START = {
  /** median start scale of entries that scale down into place */
  scaleDown: 1.13,
  scaleUp: 0.82,
  /** median start blur (px at 1080p) of entries that blur in */
  blurPx: 10.3,
  /** median |start y offset| in % of frame height for sliding entries */
  slideYPctH: 1.95,
};

export const TYPE = {
  family: '"SF Pro Display", "SF Pro", -apple-system, BlinkMacSystemFont, "Inter", "Helvetica Neue", Arial, sans-serif',
  /** cap height in % of frame height over all reviewed Apple typography: hero = p90 (event wordmarks),
   *  display = p75, headline = p50, title = p25, caption = p10 */
  capHeightPct: {hero: 20.23, display: 11.89, headline: 6.67, title: 5.43, caption: 3.25},
  /** SF Pro weight from measured stroke/cap, calibrated on renders at known weights (median 600.0) */
  weight: {hero: 600, display: 600, headline: 600, title: 600, caption: 500},
  /** line pitch / cap height 1.53 -> line-height in em for SF Pro Display */
  lineHeight: 1.079,
  letterSpacingEm: -0.015,
};

export const COLOR = {
  black: '#000000',
  white: '#ffffff',
  offWhite: '#f5f5f7',
  graphite: '#1d1d1f',
  gray: '#86868b',
  /** most frequent measured typography colours */
  measured: ["#080808", "#0b0b0b", "#0e0e0e", "#1a1a1a", "#0f0f0f", "#0c0c0d"],
};

export const MOTION = {
  /** share of Apple shots by dominant global move (the rest: local-only motion, whips) */
  mix: {static: 0.384, push: 0.155, pull: 0.197, pan: 0.091, tilt: 0.096},
  /** median |zoom| rate of push/pull shots, % scale per second (p25..p75 1.82..10.24) */
  zoomPctPerSec: 4.54,
  /** median translation rate of pan/tilt shots, % of frame per second (p25..p75 1.18..6.73) */
  panPctPerSec: 2.61,
};

export const VO = {
  /** designer type appears this many frames relative to the same spoken word (median; negative = before) */
  typeLeadFrames: -2.0,
  /** voice-over speaking rate, words per second while speaking (median of the six videos) */
  wordsPerSecond: 3.04,
};

export const AUDIO = {
  /** median integrated loudness of the Apple recaps (p10..p90 -20.4..-16.6) */
  lufs: -17.4,
  truePeakDb: -2.0,
  bpm: 118.8,
  musicUnderVoiceDb: -12,
};
