// GENERATED by scripts/build_skill_refs.py from references/fingerprint.json - do not edit by hand.
// Measured over 4 Apple recap videos (16837 frames). Medians unless noted.

export const FPS = 30;

export type SpringCfg = {damping: number; stiffness: number; mass: number};
export type Bezier = readonly [number, number, number, number];

export const SPRING = {
  /** median fitted entry spring of designer typography (n=31), corrected by the pipeline
   *  calibration (time scale 1.19). Use WITHOUT durationInFrames to reproduce the curve. */
  textIn: {damping: 15.0, stiffness: 99.9, mass: 1},
  textOut: {damping: 15.0, stiffness: 149.9, mass: 1},
  camera: {damping: 30, stiffness: 60, mass: 1},
} satisfies Record<string, SpringCfg>;

export const EASE = {
  /** median fitted cubic-bezier of typography entries */
  textIn: [0.362, 0.374, 0.521, 0.731] as Bezier,
  textOut: [0.51, 0.199, 0.575, 0.329] as Bezier,
  camera: [0.45, 0, 0.2, 1] as Bezier,
};

export const DURATION = {
  /** animated typography entries, median frames (p10..p90 4.0..30.0) */
  textInFrames: 8,
  textOutFrames: 5,
  /** typography hold, median frames (p10..p90 3.0..48.8) */
  holdFrames: 20,
  /** shot length, median frames (p10..p90 7.0..120.7) */
  shotFrames: 41,
  wordStaggerFrames: 3,
  letterStaggerFrames: 1,
  transitionFrames: 8,
};

export const START = {
  /** median start scale of entries that scale down into place */
  scaleDown: 1.1,
  scaleUp: 0.94,
  /** median start blur (px at 1080p) of entries that blur in */
  blurPx: 14.4,
  /** median |start y offset| in % of frame height for sliding entries */
  slideYPctH: 1.64,
};

export const TYPE = {
  family: '"SF Pro Display", "SF Pro", -apple-system, BlinkMacSystemFont, "Inter", "Helvetica Neue", Arial, sans-serif',
  /** cap height in % of frame height: hero = p90, headline = p50, title = p25, caption = p10 */
  capHeightPct: {hero: 20.89, headline: 9.42, title: 5.6, caption: 3.42},
  /** SF Pro weight from measured stroke/cap, calibrated on renders at known weights (median 600.0) */
  weight: {hero: 600, headline: 600, title: 600, caption: 500},
  /** line pitch / cap height 1.57 -> line-height in em for SF Pro Display */
  lineHeight: 1.107,
  letterSpacingEm: -0.015,
};

export const COLOR = {
  black: '#000000',
  white: '#ffffff',
  offWhite: '#f5f5f7',
  graphite: '#1d1d1f',
  gray: '#86868b',
  /** most frequent measured typography colours */
  measured: ["#080808", "#0e0e0e", "#0f0f0f", "#0a0a0a", "#090909", "#0b0b0b"],
};

export const AUDIO = {
  /** median integrated loudness of the Apple recaps (p10..p90 -20.2..-16.6) */
  lufs: -16.9,
  truePeakDb: -2.0,
  bpm: 109.4,
  musicUnderVoiceDb: -12,
};
