#!/usr/bin/env python3
"""Fingerprint -> skill. Regenerates, from skill/apple-motion/references/fingerprint.json:
  skill/apple-motion/references/measurements.md     every measured distribution (pooled + per video)
  skill/apple-motion/templates/remotion/tokens.ts   the defaults the components use
  skill/apple-motion/SKILL.md                       the block between <!-- numbers:start/end -->
Run after build_fingerprint.py. Hand-written guidance stays untouched.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SK = ROOT / "skill" / "apple-motion"
F = json.loads((SK / "references" / "fingerprint.json").read_text())
P = F["pooled"]
V = F["videos"]
CAP_TO_EM = 0.705  # SF Pro Display cap height / em


def g(q, k="p50", default=None):
    return q.get(k, default) if isinstance(q, dict) and q.get(k) is not None else default


def pct(x):
    return f"{x * 100:.0f}%"


def top(d, n=3):
    return ", ".join(f"{k} {pct(v) if isinstance(v, float) and v <= 1 else v}" for k, v in list(d.items())[:n])


def qrow(name, q, unit=""):
    if not q:
        return f"| {name} | n/a | | | | |"
    return f"| {name} | {q['p10']}{unit} | {q['p25']}{unit} | {q['p50']}{unit} | {q['p75']}{unit} | {q['p90']}{unit} (n={q['n']}) |"


def clamp(x, lo, hi):
    return max(lo, min(hi, x))


def entry_time():
    p = ROOT / "skill" / "apple-motion" / "references" / "entry_time.json"
    d = json.loads(p.read_text())["time_scale"] if p.exists() else {}
    items = ", ".join(f"{k}: {round(float(v), 2)}" for k, v in d.items())
    return "{" + items + "}"


def tokens():
    sp = P.get("entry_spring_calibrated") or P["entry_spring"]
    damping = sp.get("damping") or 20
    stiffness = sp.get("stiffness") or 200
    ent = g(P["entry_frames_animated"], default=12)
    ex = g(P["exit_frames"], default=6)
    hold = g(P["hold_frames"], default=45)
    shot = g(P["shot_length_frames"], default=40)
    es = P["entry_start"]
    sc = g(es.get("scale"), default=1.1)
    blur = g(es.get("blur_px"), default=10)
    dy = abs(g(es.get("dy_pct_h"), default=3))
    cap = P["cap_height_pct"]
    bz = [b if b is not None else d for b, d in zip(P["entry_bezier"], (0.2, 0.8, 0.2, 1))]
    xb = [b if b is not None else d for b, d in zip(P.get("exit_bezier", [None] * 4), (0.4, 0, 0.9, 0.5))]
    lp = g(P["line_pitch_to_cap"], default=1.5)
    line_height = round(clamp(lp * CAP_TO_EM, 0.95, 1.3), 3)
    lufs = g(P["lufs"], default=-16)
    tp = g(P["true_peak_dbtp"], default=-1.5)
    colors = list(P["color_hex"].keys())
    wt = int(g(P.get("font_weight_estimate"), default=600) or 600)
    return f"""// GENERATED by scripts/build_skill_refs.py from references/fingerprint.json - do not edit by hand.
// Measured over {P['videos']} Apple recap videos ({P['frames']} frames). Medians unless noted.

export const FPS = 30;

export type SpringCfg = {{damping: number; stiffness: number; mass: number}};
export type Bezier = readonly [number, number, number, number];

export const SPRING = {{
  /** median fitted entry spring of designer typography (n={P['entry_spring'].get('n')}), corrected by the pipeline
   *  calibration (time scale {(P.get('calibration') or {}).get('time_scale')}). Use WITHOUT durationInFrames to reproduce the curve. */
  textIn: {{damping: {round(damping, 1)}, stiffness: {round(stiffness, 1)}, mass: 1}},
  textOut: {{damping: {round(damping, 1)}, stiffness: {round(stiffness * 1.5, 1)}, mass: 1}},
  camera: {{damping: 30, stiffness: 60, mass: 1}},
}} satisfies Record<string, SpringCfg>;

export const EASE = {{
  /** median fitted cubic-bezier of typography entries */
  textIn: [{bz[0]}, {bz[1]}, {bz[2]}, {bz[3]}] as Bezier,
  textOut: [{xb[0]}, {xb[1]}, {xb[2]}, {xb[3]}] as Bezier,
  camera: [0.45, 0, 0.2, 1] as Bezier,
}};

export const DURATION = {{
  /** animated typography entries, median frames (p10..p90 {g(P['entry_frames_animated'], 'p10')}..{g(P['entry_frames_animated'], 'p90')}) */
  textInFrames: {int(round(ent))},
  textOutFrames: {max(2, int(round(ex)))},
  /** typography hold, median frames (p10..p90 {g(P['hold_frames'], 'p10')}..{g(P['hold_frames'], 'p90')}) */
  holdFrames: {int(round(hold))},
  /** shot length, median frames (p10..p90 {g(P['shot_length_frames'], 'p10')}..{g(P['shot_length_frames'], 'p90')}) */
  shotFrames: {int(round(shot))},
  wordStaggerFrames: {int(round(g(P.get('word_stagger_frames') or dict(), default=3) or 3))},
  letterStaggerFrames: 1,
  transitionFrames: 8,
}};

export const START = {{
  /** median start scale of entries that scale down into place */
  scaleDown: {round(g(P.get('entry_start_scale_down'), default=1.1), 3)},
  scaleUp: {round(g(P.get('entry_start_scale_up'), default=0.93), 3)},
  /** median start blur (px at 1080p) of entries that blur in */
  blurPx: {round(blur, 1)},
  /** median |start y offset| in % of frame height for sliding entries */
  slideYPctH: {round(dy, 2)},
}};

export const TYPE = {{
  family: '"SF Pro Display", "SF Pro", -apple-system, BlinkMacSystemFont, "Inter", "Helvetica Neue", Arial, sans-serif',
  /** cap height in % of frame height over all reviewed Apple typography: hero = p90 (event wordmarks),
   *  display = p75, headline = p50, title = p25, caption = p10 */
  capHeightPct: {{hero: {g(cap, 'p90', 12)}, display: {g(cap, 'p75', 10)}, headline: {g(cap, 'p50', 7)}, title: {g(cap, 'p25', 4.5)}, caption: {g(cap, 'p10', 2.6)}}},
  /** SF Pro weight from measured stroke/cap, calibrated on renders at known weights (median {g(P.get('font_weight_estimate'), default='n/a')}) */
  weight: {{hero: {wt}, display: {wt}, headline: {wt}, title: {wt}, caption: {max(400, wt - 100)}}},
  /** line pitch / cap height {lp} -> line-height in em for SF Pro Display */
  lineHeight: {line_height},
  letterSpacingEm: -0.015,
}};

export const COLOR = {{
  black: '#000000',
  white: '#ffffff',
  offWhite: '#f5f5f7',
  graphite: '#1d1d1f',
  gray: '#86868b',
  /** most frequent measured typography colours */
  measured: {json.dumps(colors[:6])},
}};

/** Per-entry spring time scale, trained: calibration renders at several speeds were measured with the
 *  extraction pipeline and each entry type was set to the speed whose measured entry length matches
 *  Apple's median for that type (scripts/train_entries.py, reports/eval/entry-training.md). */
export const ENTRY_TIME = {entry_time()} as const;

export const MOTION = {{
  /** share of Apple shots by dominant global move (the rest: local-only motion, whips) */
  mix: {{static: {P['dominant_move'].get('static', 0.38)}, push: {P['dominant_move'].get('push', 0.16)}, pull: {P['dominant_move'].get('pull', 0.2)}, pan: {P['dominant_move'].get('pan', 0.09)}, tilt: {P['dominant_move'].get('tilt', 0.1)}}},
  /** median |zoom| rate of push/pull shots, % scale per second (p25..p75 {g(P['camera']['zoom_pct_per_s'], 'p25')}..{g(P['camera']['zoom_pct_per_s'], 'p75')}) */
  zoomPctPerSec: {g(P['camera']['zoom_pct_per_s'], default=4.5)},
  /** median translation rate of pan/tilt shots, % of frame per second (p25..p75 {g(P['camera']['pan_pct_per_s'], 'p25')}..{g(P['camera']['pan_pct_per_s'], 'p75')}) */
  panPctPerSec: {g(P['camera']['pan_pct_per_s'], default=2.6)},
}};

export const VO = {{
  /** designer type appears this many frames relative to the same spoken word (median; negative = before) */
  typeLeadFrames: {g(P['typography_vo_offset_frames'], default=-2)},
  /** voice-over speaking rate, words per second while speaking (median of the six videos) */
  wordsPerSecond: {g(P['vo_words_per_s_speaking'], default=3.0)},
}};

export const AUDIO = {{
  /** median integrated loudness of the Apple recaps (p10..p90 {g(P['lufs'], 'p10')}..{g(P['lufs'], 'p90')}) */
  lufs: {lufs},
  truePeakDb: {tp},
  bpm: {g(P['bpm'], default=120)},
  musicUnderVoiceDb: -12,
}};
"""


def measurements():
    L = ["# Measurements", "", f"Pooled over {P['videos']} videos, {P['duration_s']} s, {P['frames']} frames. "
         "Generated from fingerprint.json - numbers only. Frames at ~30 fps.", "",
         "## Distributions (pooled)", "", "| metric | p10 | p25 | p50 | p75 | p90 |", "|---|---|---|---|---|---|",
         qrow("shot length (frames)", P["shot_length_frames"]),
         qrow("cuts per 10 s (per video)", P["cuts_per_10s"]),
         qrow("typography events per 10 s (per video)", P["typography_per_10s"]),
         qrow("cap height (% of frame height)", P["cap_height_pct"]),
         qrow("stroke / cap height (weight proxy)", P["stroke_to_cap"]),
         qrow("estimated SF Pro weight (calibrated)", P.get("font_weight_estimate")),
         qrow("x-height / cap height", P["x_height_ratio"]),
         qrow("line pitch / cap height", P["line_pitch_to_cap"]),
         qrow("typography hold (frames)", P["hold_frames"]),
         qrow("typography on screen (frames)", P["on_screen_frames"]),
         qrow("entry duration, all (frames)", P["entry_frames"]),
         qrow("entry duration, animated only (frames)", P["entry_frames_animated"]),
         qrow("exit duration (frames)", P["exit_frames"]),
         qrow("entry start scale", P["entry_start"]["scale"]),
         qrow("entry start y offset (% of height)", P["entry_start"]["dy_pct_h"]),
         qrow("entry start blur (px @1080p)", P["entry_start"]["blur_px"]),
         qrow("hold drift, scale (%/s)", P["hold_drift_scale_pct_per_s"]),
         qrow("entry spring damping (good fits)", P["entry_spring_q"]["damping"]),
         qrow("entry spring stiffness (good fits)", P["entry_spring_q"]["stiffness"]),
         qrow("entry spring durationInFrames", P["entry_spring_q"]["durationInFrames"]),
         qrow("music BPM (per video)", P["bpm"]),
         qrow("integrated loudness LUFS (per video)", P["lufs"]),
         qrow("true peak dBTP (per video)", P["true_peak_dbtp"]),
         qrow("loudness range LU (per video)", P["lra_lu"]),
         qrow("VO words/s while speaking (per video)", P["vo_words_per_s_speaking"]),
         qrow("SFX candidates per 10 s (per video)", P["sfx_per_10s"]),
         qrow("cuts on beat +-2 fr (per video)", P["cuts_on_beat"]),
         qrow("chance of on-beat (per video)", P["chance_on_beat"]),
         qrow("cuts near a word onset +-2 fr", P["cuts_near_word_onset"]),
         qrow("chance near a word onset", P["chance_near_word_onset"]),
         qrow("typography appear - same spoken word (frames)", P["typography_vo_offset_frames"]),
         qrow("UI/graphic element entries per s", P["element_entries_per_s"]),
         qrow("camera zoom rate, push/pull shots (%/s)", P["camera"]["zoom_pct_per_s"]),
         qrow("camera pan/tilt rate (% of frame/s)", P["camera"]["pan_pct_per_s"]),
         qrow("first shot (frames)", P.get("first_shot_frames")),
         qrow("last shot (frames)", P.get("last_shot_frames")),
         qrow("montage runs (>=4 shots of <=10 fr) per minute", P.get("montage_runs_per_minute")),
         "", "## Shares (pooled)", "",
         f"- Transitions: {top(P['transitions'], 6)}",
         f"- Typography entry styles: {top(P['entry_style'], 8)}",
         f"- Typography exit styles: {top(P['exit_style'], 6)}",
         f"- Appear kind: {top(P['appear_kind'])}; exit kind: {top(P['exit_kind'])}",
         f"- Animated channels in entries: {top(P['entry_channels'], 6)}",
         f"- Entry spring (median of good fits): damping {P['entry_spring']['damping']}, stiffness {P['entry_spring']['stiffness']}, "
         f"mass 1, durationInFrames {P['entry_spring']['durationInFrames']}, zeta {P['entry_spring']['zeta']}, overshoot "
         f"{P['entry_spring']['overshoot_pct']}%, n={P['entry_spring']['n']}",
         f"- Calibrated entry spring (pipeline speed bias removed, see calibration): {P.get('entry_spring_calibrated')} - "
         f"use damping/stiffness/mass WITHOUT durationInFrames; durationInFrames here is only Remotion's natural settle "
         f"length (measureSpring), for reference; "
         f"calibration {json.dumps(P.get('calibration'))}",
         f"- Median shot length by quarter of the video: {P.get('median_shot_by_quarter')} frames; share of typography per quarter: "
         f"{P.get('typography_share_by_quarter')}",
         f"- Cuts on the beat, pooled: {json.dumps(P.get('cuts_on_beat_pooled'))}",
         f"- Idiomatic form: spring({{config: {{damping: {P['entry_spring_idiomatic']['damping']}}}, durationInFrames: "
         f"{P['entry_spring_idiomatic']['durationInFrames']}}}) (stiffness 100, mass 1)",
         f"- Entry cubic-bezier (median control points): {P['entry_bezier']}; nearest named: {top(P['entry_bezier_named'], 4)}",
         f"- Exit cubic-bezier (median): {P['exit_bezier']}",
         f"- Line count: {top(P['line_count'], 4)}; alignment: {top(P['alignment'], 4)}",
         f"- Position (3x3 grid): {top(P['grid_cell'], 6)}",
         f"- Typography colour (most frequent hex): {', '.join(list(P['color_hex'])[:6])}",
         f"- Background behind typography: {top(P['background_type'], 3)}",
         f"- Frame classes (mean share of frames): {top(dict(sorted(P['frame_share_by_class'].items(), key=lambda kv: -kv[1])), 6)}",
         f"- Global motion per shot: {top(P['dominant_move'], 7)}",
         "", "## Per video", "",
         "| video | dur s | shots | median shot fr | cuts/10s | typo/10s | median hold fr | top entry | BPM | LUFS | cuts on beat (chance) |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for v in V:
        es = v["typography"]["entry_style"]
        L.append(f"| {v['slug']} | {v['duration_s']} | {v['shots']['count']} | {g(v['shots']['length_frames'])} | "
                 f"{v['shots']['cuts_per_10s']} | {v['text']['typography_per_10s']} | {g(v['typography']['hold_frames'])} | "
                 f"{max(es, key=es.get) if es else 'n/a'} | {v['audio']['bpm']} | {v['audio']['loudness']['integrated_lufs']} | "
                 f"{v['sync']['cuts_on_beat']} ({v['sync']['chance_on_beat']}) |")
    L += ["", "## Typography examples (reviewed)", ""]
    for v in V:
        for e in v["typography"]["examples"][:12]:
            L.append(f"- {v['slug']} f{e['appear']}: \"{e['text'][:50]}\" - {e['entry']}, entry {e['entry_frames']} fr, "
                     f"hold {e['hold']} fr, cap {e['cap_pct']}%, {e['color']} on {e['bg']}")
    return "\n".join(L) + "\n"


def numbers_block():
    sp = P.get("entry_spring_calibrated") or P["entry_spring"]
    pb = P.get("cuts_on_beat_pooled") or {}
    if pb and pb.get("p_one_sided") is not None and pb["p_one_sided"] < 0.05:
        sync = (f"Cuts favour the beat: {pb['hits']}/{pb['cuts']} within +-2 frames vs {pb['expected_by_chance']} expected by "
                f"chance (p={pb['p_one_sided']}).")
    else:
        sync = (f"Cuts are not locked to the beat: {pb.get('hits')}/{pb.get('cuts')} within +-2 frames vs "
                f"{pb.get('expected_by_chance')} expected by chance (p={pb.get('p_one_sided')}) - the edit follows the voice and picture.")
    return "\n".join([
        f"- **Pace.** Median shot {g(P['shot_length_frames'])} frames ({g(P['shot_length_frames']) / 30:.1f} s); "
        f"p10 {g(P['shot_length_frames'], 'p10')}, p90 {g(P['shot_length_frames'], 'p90')} frames; "
        f"{g(P['cuts_per_10s'])} cuts per 10 s (median video). Transitions: {top(P['transitions'], 4)}.",
        f"- **Typography is an accent, not the bed.** Designer-set type appears {g(P['typography_per_10s'])} times per 10 s "
        f"(median video); most on-screen text is UI inside product shots. Hold {g(P['hold_frames'])} frames median "
        f"(p10 {g(P['hold_frames'], 'p10')}, p90 {g(P['hold_frames'], 'p90')}).",
        f"- **Size.** Cap height median {g(P['cap_height_pct'])}% of frame height (p10 {g(P['cap_height_pct'], 'p10')}%, "
        f"p90 {g(P['cap_height_pct'], 'p90')}%). Lines: {top(P['line_count'], 3)}. Alignment: {top(P['alignment'], 3)}.",
        f"- **Entries.** {top(P['entry_style'], 5)}. Animated entries are visibly done in {g(P['entry_frames_animated'])} frames "
        f"(median). Spring (calibrated): damping {sp.get('damping')}, stiffness {sp.get('stiffness')}, mass 1 - use it "
        f"without durationInFrames.",
        f"- **Exits.** {top(P['exit_style'], 4)}; median {g(P['exit_frames'])} frames.",
        f"- **Sound.** {g(P['bpm'])} BPM median (p10 {g(P['bpm'], 'p10')}, p90 {g(P['bpm'], 'p90')}); "
        f"{g(P['lufs'])} LUFS integrated, {g(P['true_peak_dbtp'])} dBTP true peak; voice-over at "
        f"{g(P['vo_words_per_s_speaking'])} words/s. {sync}",
    ])


def readme_results():
    rep = (ROOT / "reports" / "extraction_report.md").read_text()
    table = rep[rep.index("| video |"):rep.index("\n\n", rep.index("| video |"))]
    sp = P.get("entry_spring_calibrated") or {}
    lines = ["## Results", "", f"{P['videos']} videos, {P['duration_s']} s, {P['frames']} frames. Full report: "
             "[`reports/extraction_report.md`](reports/extraction_report.md), distributions: "
             "[`skill/apple-motion/references/measurements.md`](skill/apple-motion/references/measurements.md).", "",
             table, "",
             f"Pooled: median shot {g(P['shot_length_frames'])} frames, typography cap height {g(P['cap_height_pct'])}% of frame "
             f"height (~SF Pro {g(P.get('font_weight_estimate'), default='?')}), typography hold {g(P['hold_frames'])} frames, "
             f"calibrated entry spring damping {sp.get('damping')} / stiffness {sp.get('stiffness')} / mass 1, "
             f"{g(P['lufs'])} LUFS."]
    return "\n".join(lines)


def main():
    rd = ROOT / "README.md"
    if rd.exists() and (ROOT / "reports" / "extraction_report.md").exists():
        r = rd.read_text()
        r = re.sub(r"<!-- results:start -->.*?<!-- results:end -->",
                   "<!-- results:start -->\n" + readme_results() + "\n<!-- results:end -->", r, flags=re.S)
        rd.write_text(r)
    (SK / "templates" / "remotion" / "tokens.ts").write_text(tokens())
    (SK / "references" / "measurements.md").write_text(measurements())
    s = (SK / "SKILL.md").read_text()
    s = re.sub(r"<!-- numbers:start -->.*?<!-- numbers:end -->",
               "<!-- numbers:start -->\n" + numbers_block() + "\n<!-- numbers:end -->", s, flags=re.S)
    (SK / "SKILL.md").write_text(s)
    print("tokens.ts, measurements.md, SKILL.md numbers block regenerated")


if __name__ == "__main__":
    main()
